"use client";
import {useEffect,useState} from "react"; import {supabase} from "@/lib/supabase/client"; import {MATERIAL_TYPE_LABELS,SEMESTER_LABELS} from "@/lib/types";
const input="w-full rounded-2xl border border-olive/10 bg-[#fbfaf7] px-4 py-3 text-sm text-ink outline-none focus:border-gold focus:bg-white focus:ring-4 focus:ring-gold/10";
export default function SubmitPage(){
 const[session,setSession]=useState<any>(null),[courses,setCourses]=useState<any[]>([]),[faculties,setFaculties]=useState<any[]>([]),[mode,setMode]=useState<"material"|"course">("material");
 const[course,setCourse]=useState(""),[title,setTitle]=useState(""),[desc,setDesc]=useState(""),[type,setType]=useState<any>("exam"),[year,setYear]=useState(""),[sem,setSem]=useState(""),[link,setLink]=useState(""),[faculty,setFaculty]=useState(""),[courseName,setCourseName]=useState(""),[courseCode,setCourseCode]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href="/auth";return}setSession(session);const [{data:c},{data:f}]=await Promise.all([supabase.from("courses").select("id,name_ar,code,faculties(name_ar,universities(name_ar))").order("name_ar"),supabase.from("faculties").select("id,name_ar,universities(name_ar)").order("name_ar")]);setCourses(c||[]);setFaculties(f||[])})()},[]);
 async function saveMaterial(e:any){e.preventDefault();setBusy(true);setMsg("");const r=await fetch("/api/submissions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({course_id:course,title_ar:title,description_ar:desc,type,academic_year:year,semester:sem,drive_link:type==="video"?"":link,youtube_input:type==="video"?link:""})});const d=await r.json();setBusy(false);setMsg(r.ok?"تم إرسال المحتوى للمراجعة والموافقة.":d.error||"تعذر الإرسال");if(r.ok){setTitle("");setDesc("");setLink("")}}
 async function saveCourse(e:any){e.preventDefault();setBusy(true);setMsg("");const r=await fetch("/api/admin/course-requests",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({faculty_id:faculty,name_ar:courseName,code:courseCode})});const d=await r.json();setBusy(false);setMsg(r.ok?"تم إرسال طلب إضافة المساق وسيظهر بعد موافقة المسؤول.":d.error||"تعذر الإرسال");if(r.ok){setCourseName("");setCourseCode("")}}
 return <main className="min-h-[70vh] bg-[#f7f5ef] px-5 py-10"><div className="mx-auto max-w-2xl"><div className="rounded-[32px] bg-olive p-7 text-parchment shadow-soft sm:p-9"><p className="text-xs font-black tracking-[.2em] text-gold-light">PUSH · CONTRIBUTION</p><h1 className="mt-2 font-display text-4xl font-bold">إضافة محتوى</h1><p className="mt-3 text-sm leading-7 text-parchment/65">الإضافات من المستخدمين تحتاج موافقة الإدارة قبل النشر.</p></div><div className="mt-5 grid grid-cols-2 gap-2 rounded-2xl bg-white p-2 shadow-card"><button onClick={()=>setMode("material")} className={`rounded-xl py-3 font-black ${mode==="material"?"bg-olive text-parchment":"text-ink/50"}`}>إضافة محتوى لمساق</button><button onClick={()=>setMode("course")} className={`rounded-xl py-3 font-black ${mode==="course"?"bg-olive text-parchment":"text-ink/50"}`}>طلب إضافة مساق</button></div>
 {mode==="material"?<form onSubmit={saveMaterial} className="mt-5 rounded-[28px] border border-olive/10 bg-white p-6 shadow-card sm:p-8 space-y-3"><select required value={course} onChange={e=>setCourse(e.target.value)} className={input}><option value="">اختر المساق</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name_ar} · {c.code} — {c.faculties?.name_ar}</option>)}</select><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان المحتوى" className={input}/><textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={3} placeholder="وصف اختياري" className={`${input} resize-none`}/><div className="grid gap-3 sm:grid-cols-2"><select value={type} onChange={e=>setType(e.target.value)} className={input}>{Object.entries(MATERIAL_TYPE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={sem} onChange={e=>setSem(e.target.value)} className={input}><option value="">الفصل</option>{Object.entries(SEMESTER_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><input value={year} onChange={e=>setYear(e.target.value)} placeholder="العام الدراسي (اختياري)" className={input}/><input required value={link} onChange={e=>setLink(e.target.value)} placeholder={type==="video"?"رابط YouTube":"رابط Google Drive"} className={input}/><button disabled={busy} className="w-full rounded-2xl bg-clay py-3.5 font-black text-parchment">{busy?"جارٍ الإرسال...":"إرسال للمراجعة"}</button></form>:<form onSubmit={saveCourse} className="mt-5 rounded-[28px] border border-olive/10 bg-white p-6 shadow-card sm:p-8 space-y-3"><select required value={faculty} onChange={e=>setFaculty(e.target.value)} className={input}><option value="">اختر الكلية</option>{faculties.map(f=><option key={f.id} value={f.id}>{f.name_ar} — {f.universities?.name_ar}</option>)}</select><input required value={courseName} onChange={e=>setCourseName(e.target.value)} placeholder="اسم المساق" className={input}/><input required value={courseCode} onChange={e=>setCourseCode(e.target.value)} placeholder="رقم/رمز المساق (إجباري)" className={input}/><button disabled={busy} className="w-full rounded-2xl bg-clay py-3.5 font-black text-parchment">{busy?"جارٍ الإرسال...":"إرسال طلب المساق"}</button></form>}
 {msg&&<div className="mt-4 rounded-2xl bg-olive/5 p-4 text-sm font-bold text-olive-dark">{msg}</div>}</div></main>
}