"use client";
import Link from "next/link";import{useEffect,useState}from"react";import{supabase}from"@/lib/supabase/client";
const input="w-full rounded-2xl border border-olive/10 bg-[#fbfaf7] px-4 py-3 text-sm outline-none";
export default function AccountPage(){
 const[user,setUser]=useState<any>(null),[profile,setProfile]=useState<any>(null),[items,setItems]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[edit,setEdit]=useState<any>(null),[gear,setGear]=useState(false);
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/auth";return}setUser(user);const{data:p}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();setProfile(p);const{data:{session}}=await supabase.auth.getSession();if(session){const r=await fetch("/api/submissions",{headers:{Authorization:`Bearer ${session.access_token}`}});if(r.ok){const d=await r.json();setItems(d.published||[]);setRequests(d.courseRequests||[])}}}
 useEffect(()=>{load()},[]);
 async function logout(){await supabase.auth.signOut();window.location.href="/"}
 async function remove(id:string){if(!confirm("حذف المنشور؟"))return;const{data:{session}}=await supabase.auth.getSession();const r=await fetch(`/api/submissions?id=${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${session?.access_token}`}});const d=await r.json();if(!r.ok)alert(d.error||"تعذر الحذف");else load()}
 async function save(){const{data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/submissions",{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({id:edit.id,title_ar:edit.title_ar,description_ar:edit.description_ar})});const d=await r.json();if(!r.ok)alert(d.error||"تعذر التعديل");else{setEdit(null);load()}}
 if(!user)return <main className="min-h-[70vh]"/>;
 const roleLabel=profile?.role==="owner"?"المالك":profile?.role==="admin"?"المسؤول":"مستخدم عادي";
 const within6=(x:string)=>Date.now()-new Date(x).getTime()<=6*60*60*1000;
 return <main className="min-h-[70vh] bg-[#f7f5ef] px-5 py-10"><div className="mx-auto max-w-5xl"><div className="relative rounded-[32px] bg-olive p-7 text-parchment shadow-soft sm:p-9"><button onClick={()=>setGear(true)} aria-label="إعدادات الحساب" className="absolute left-5 top-5 rounded-2xl bg-white/10 p-3 text-xl">⚙</button><div><p className="text-xs font-black tracking-[.2em] text-gold-light">PUSH · ACCOUNT</p><h1 className="mt-2 font-display text-4xl font-bold">{profile?.full_name||user.email}</h1><p className="mt-2 text-sm text-parchment/60">{user.email} · {roleLabel}</p></div></div>
 <section className="mt-7 rounded-[28px] border border-olive/10 bg-white p-6 shadow-card"><div className="flex items-center justify-between"><div><h2 className="font-display text-2xl font-bold text-olive-dark">سجل منشوراتي</h2><p className="mt-1 text-sm text-ink/50">يمكنك تعديل أو حذف منشورك خلال 6 ساعات من النشر فقط.</p></div><Link href="/submit" className="rounded-2xl bg-clay px-4 py-3 text-sm font-black text-parchment">+ إضافة</Link></div><div className="mt-5 space-y-3">{items.map(x=><article key={x.id} className="rounded-2xl border border-olive/10 bg-[#fbfaf7] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-bold text-olive-dark">{x.title_ar}</div><div className="mt-1 text-xs text-ink/45">{x.courses?.name_ar} · {x.courses?.code} · {new Date(x.created_at).toLocaleString("ar")}</div></div>{within6(x.created_at)?<div className="flex gap-2"><button onClick={()=>setEdit({...x})} className="rounded-xl border border-olive/10 px-3 py-2 text-xs font-black">تعديل</button><button onClick={()=>remove(x.id)} className="rounded-xl border border-clay/15 px-3 py-2 text-xs font-black text-clay-dark">حذف</button></div>:<span className="text-xs font-bold text-ink/35">انتهت مهلة التعديل · تواصل مع الإدارة</span>}</div></article>)}{!items.length&&<p className="p-10 text-center text-sm text-ink/40">لا توجد منشورات منشورة باسمك بعد.</p>}</div></section>
 <section className="mt-7 rounded-[28px] border border-olive/10 bg-white p-6 shadow-card"><h2 className="font-display text-2xl font-bold text-olive-dark">طلبات إضافة المساقات</h2><div className="mt-4 space-y-2">{requests.map(x=><div key={x.id} className="rounded-2xl bg-[#fbfaf7] p-4"><b>{x.name_ar}</b> · {x.code}<span className="mr-3 text-xs font-black">{x.status==="pending"?"قيد المراجعة":x.status==="approved"?"تمت الموافقة":"مرفوض"}</span></div>)}{!requests.length&&<p className="text-sm text-ink/40">لا توجد طلبات.</p>}</div></section>
 {gear&&<div className="fixed inset-0 z-50 grid place-items-center bg-olive/35 p-5 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[28px] bg-white p-6 shadow-soft"><div className="flex justify-between"><h3 className="font-display text-2xl font-bold text-olive-dark">إعدادات الحساب والإضافات</h3><button onClick={()=>setGear(false)}>✕</button></div><div className="mt-5 space-y-2 text-sm"><div className="rounded-2xl bg-[#fbfaf7] p-4"><b>الاسم:</b> {profile?.full_name||"غير محدد"}<br/><b>البريد:</b> {user.email}<br/><b>الصلاحية:</b> {roleLabel}</div><Link href="/submit" className="block rounded-2xl bg-olive p-4 font-black text-parchment">إضافة محتوى لمساق</Link><Link href="/submit" className="block rounded-2xl border border-olive/10 p-4 font-black text-olive-dark">طلب إضافة مساق</Link><button onClick={logout} className="w-full rounded-2xl bg-clay p-4 font-black text-parchment">تسجيل الخروج</button></div></div></div>}
 {edit&&<div className="fixed inset-0 z-50 grid place-items-center bg-olive/35 p-5 backdrop-blur-sm"><div className="w-full max-w-lg rounded-[28px] bg-white p-6"><h3 className="font-display text-2xl font-bold text-olive-dark">تعديل المنشور</h3><input className={`${input} mt-5`} value={edit.title_ar} onChange={e=>setEdit({...edit,title_ar:e.target.value})}/><textarea className={`${input} mt-3 resize-none`} rows={4} value={edit.description_ar||""} onChange={e=>setEdit({...edit,description_ar:e.target.value})}/><div className="mt-4 flex gap-2"><button onClick={save} className="flex-1 rounded-2xl bg-olive p-3 font-black text-parchment">حفظ</button><button onClick={()=>setEdit(null)} className="rounded-2xl border p-3 font-black">إلغاء</button></div></div></div>}</div></main>
}